version: 2

models:
  # Staging Models
  - name: stg_nypd_arrest
    description: "Staging table for NYPD arrest data with cleaned and validated records"
    columns:
      - name: arrest_key
        description: "Unique identifier for each arrest record"
        tests:
          - not_null
          - unique
      - name: arrest_date
        description: "Date when the arrest occurred"
        tests:
          - not_null
      - name: pd_id
        description: "PD code from NYPD arrest data"
        tests:
          - not_null
      - name: ky_id
        description: "KY code from NYPD arrest data"
        tests:
          - not_null

  - name: stg_dim_pd
    description: "Staging dimension table for PD codes and descriptions"
    columns:
      - name: pd_id
        description: "PD code (natural business key)"
        tests:
          - not_null
          - unique
      - name: pd_desc
        description: "PD description"
        tests:
          - not_null

  - name: stg_dim_ky
    description: "Staging dimension table for KY codes and descriptions"
    columns:
      - name: ky_id
        description: "KY code (natural business key)"
        tests:
          - not_null
          - unique
      - name: ofns_desc
        description: "Offense description"
        tests:
          - not_null

  # DWH Models
  - name: dwh_dim_pd
    description: "DWH dimension table for PD data with SCD Type 1 implementation"
    columns:
      - name: pd_id
        description: "PD code (natural business key)"
        tests:
          - not_null
          - unique
      - name: pd_desc
        description: "Current PD description (SCD Type 1)"
        tests:
          - not_null

  - name: dwh_dim_ky
    description: "DWH dimension table for KY data with SCD Type 1 implementation"
    columns:
      - name: ky_id
        description: "KY code (natural business key)"
        tests:
          - not_null
          - unique
      - name: ofns_desc
        description: "Current offense description (SCD Type 1)"
        tests:
          - not_null

  - name: dwh_nypd_arrest
    description: "DWH fact table for NYPD arrest data with full historical records, partitioned by date"
    columns:
      - name: arrest_key
        description: "Unique identifier for each arrest record"
        tests:
          - not_null
          - unique
      - name: arrest_date
        description: "Date when the arrest occurred"
        tests:
          - not_null
      - name: partition_date
        description: "Partition date for historical data management"
        tests:
          - not_null
      - name: pd_id
        description: "PD code (foreign key to dwh_dim_pd)"
        tests:
          - not_null
          # Relationship test commented out until build order is resolved
          # - relationships:
          #     to: ref('dwh_dim_pd')
          #     field: pd_id
      - name: ky_id
        description: "KY code (foreign key to dwh_dim_ky)"
        tests:
          - not_null
          # Relationship test commented out until build order is resolved
          # - relationships:
          #     to: ref('dwh_dim_ky')
          #     field: ky_id